language: go

go:
  - "1.14.x"

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_USER='1234'

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.24.0

before_script:
  - psql -c 'create database list_expense_test;' -U postgres
  - go env

script: "make lint && make test"
