language: go

services:
  - postgresql
addons:
  postgresql: "10"

env:
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_USER='1234'

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

before_script:
  - psql -c 'create database list_expense_test;' -U postgres
  - go env

script: "make lint"


#script: "go test ./... -v -race -timeout 120s -count=1"
