package postgres

const Schema = `
			CREATE TABLE IF NOT EXISTS spents (
			  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			  name          VARCHAR(256) NOT NULL,
			  amount        DECIMAL(12,2) NOT NULL, 
			  created_at    TIMESTAMP(6) NOT NULL,
			  updated_at    TIMESTAMP(6) NOT NULL
			);
			`
